### PR TITLE
Db hosts

### PR DESCRIPTION
**Pull request by lokal-profil**
Make hostbot more flexible with regards to which databases/tables it uses.

To do this `hb_queries` has been rewritten and additional variables have been added to `hb_config`

Also:
- Add undocumented config variables
- Rename `hb_config.sample`
- Hack to add root directory to sys path
- Add  requirements.txt for use by venv
- Drop use of `sample_type` and `sample_group` columns

### CODE REVIEW

**Comment by lokal-profil** [comment]
We might possibly also want to add the sql file for initial table setup?

**Comment by lokal-profil** [comment]
Might also be worth noting that this likely breaks every script other than `scripts/teahouse/send_th_invites.py`

**Comment by BenignBeppe** [comment]
Changes look good to me. Maybe you should update the copyright notices with year and author.

**Comment by lokal-profil** [comment]
Added copyright update to `hb_queries` and `hb_toolkit`

**Pull request merged**
